apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/back-golang
- ../../base/front-javascript
namespace: multienvapp-production
commonLabels:
  version: v1
  env: production