apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
namePrefix: imageapp-
namespace: imageapp
images:
- name: testing
  newName: quay.io/acidonpe/jump-app-front-javascript
  newTag: latest